### ISSUE TITLE
Android 6.0 Camera Issue

### ISSUE THREAD

**Issue by danilo-favoratti** [d2soft/NimbbLibrary-Android#1]
I got this in my app, but the same occurs in DemoProject.

MotoX (2nd generation) - Android 6.0

```
FATAL EXCEPTION: main
                                                                           Process: br.com.presume.presumeapp, PID: 13518
                                                                           java.lang.RuntimeException: Unable to start activity ComponentInfo{br.com.presume.presumeapp/com.nimbb.recorder.RecorderActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'android.hardware.Camera$Parameters android.hardware.Camera.getParameters()' on a null object reference
                                                                               at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2426)
                                                                               at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2490)
                                                                               at android.app.ActivityThread.-wrap11(ActivityThread.java)
                                                                               at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1354)
                                                                               at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                               at android.os.Looper.loop(Looper.java:148)
                                                                               at android.app.ActivityThread.main(ActivityThread.java:5443)
                                                                               at java.lang.reflect.Method.invoke(Native Method)
                                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
                                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)
                                                                            Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.hardware.Camera$Parameters android.hardware.Camera.getParameters()' on a null object reference
                                                                               at com.nimbb.recorder.RecorderActivity.getVideoSizeFromQualityParam(RecorderActivity.java:158)
                                                                               at com.nimbb.recorder.RecorderActivity.displayCameraPreview(RecorderActivity.java:127)
                                                                               at com.nimbb.recorder.RecorderActivity.onCreate(RecorderActivity.java:61)
                                                                               at android.app.Activity.performCreate(Activity.java:6245)
                                                                               at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1130)
                                                                               at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2379)
                                                                               at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2490) 
                                                                               at android.app.ActivityThread.-wrap11(ActivityThread.java) 
                                                                               at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1354) 
                                                                               at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                               at android.os.Looper.loop(Looper.java:148) 
                                                                               at android.app.ActivityThread.main(ActivityThread.java:5443) 
                                                                               at java.lang.reflect.Method.invoke(Native Method) 
                                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728) 
                                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618) 
```

**Comment by danilo-favoratti** [comment]
Maybe the problem is caused by deprecated _android.hardware.camera_ in API Level 21.

http://developer.android.com/intl/pt-br/reference/android/hardware/Camera.html
